# language: node_js
# node_js: 
#   - "11.14.0"

# sudo: true

# install: true  # yarn bug

# services:
#   - docker

# #addons:
# #  firefox: "45.0"

# branches:
#   only: master

# os:
#   - linux
# #  - osx

# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated xctool || brew upgrade xctool; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi  # Karma CI
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install google-chrome; fi  # Karma CI
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
#   #Set up Docker exports
#   - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
#   - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
#   - export AUTHOR=`git --no-pager show -s --format='%an <%ae>'`
#   - export DATE=`TZ=America/New_York date "+%m-%d-%y-%H%M"`
#   - export DATE_TM=`TZ=America/New_York date "+%m-%d-%y %H:%M"`


# before_script:
#   - node --version
#   - npm install -g npm
#   - npm install
#   - curl -O https://bootstrap.pypa.io/get-pip.py
#   - sudo python3 get-pip.py
#   - pip --version
#   - pip install awscli --upgrade --user

# script:
#   - mkdir coverage
#   - npm run test
#   - npm install
#   - npm run build -- --mode prod
#   - sed -i -e "s/I___UI_BUILD_TIME___I/$DATE_TM/g" ./dist/js/*.js*

# after_failure:
# #  - cat /home/travis/build/nci-strap-ui/npm-debug.log

# after_success:
#   #Deploy to int S3
#   - cat coverage/lcov.info | ./node_modules/.bin/codacy-coverage
#   - cd dist
#   - zip -r dlap-ui.$DATE.zip ./
#   - aws s3 cp dlap-ui.$DATE.zip s3://www.dlap.int/dlap-ui.$DATE.zip

# ## Remove once BDD Tests setup
#   - export INT_AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
#   - export INT_AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
#   - git clone https://$GIT_TOKEN@github.com/BIAD/cloud_deploy.git
#   - cd cloud_deploy
#   - bundle install
#   - bin/cloud_deploy deploy_now -p dlap -t int -r nci-dlap-ui -v $DATE
#   - curl -s -X POST -H "Content-Type:application/json" -H "Accept:application/json" -H "Travis-API-Version:3" -H "Authorization:token $TRAVIS_TOKEN" -d "{\"request\":{\"message\":\"Triggered by nci-dlap-ui $TRAVIS_COMMIT\", \"branch\":\"master\", \"config\":{\"env\":{\"matrix\":[\"TRIGGER_REPO=nci-dlap-ui;TRIGGER_VER=$DATE;TRIGGER_COMMIT=$TRAVIS_COMMIT;AUTHOR=$AUTHOR\"]}}}}" https://api.travis-ci.com/repo/BIAD%2Fnci-dlap-bddtests/requests

# notifications:
#   slack: clinicalbiomed:6zDFHis6gxhTE2hBzggh9Tma



# #cache: pip


# notifications:
#   slack: clinicalbiomed:6zDFHis6gxhTE2hBzggh9Tma

# #cache:
# #  directories: node_modules
